import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.FileWriter;
import java.io.IOException;

public class PessoaFrame extends javax.swing.JFrame {

    private JTextField txtNome, txtIdade, txtApelido;
    private JButton btnCriar;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PessoaFrame.class.getName());

    /**
     * Creates new form PessoaFrame
     */
    public PessoaFrame() {
        super("Cadastro de Pessoa");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 250);
        setLocationRelativeTo(null);

        // Painel principal
        JPanel painel = new JPanel();
        painel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        c.insets = new Insets(5, 5, 5, 5); // espaço entre componentes
        c.fill = GridBagConstraints.HORIZONTAL;

        // Nome
        c.gridx = 0;
        c.gridy = 0;
        painel.add(new JLabel("Nome:"), c);
        c.gridx = 1;
        txtNome = new JTextField(20);
        painel.add(txtNome, c);

        // Idade
        c.gridx = 0;
        c.gridy = 1;
        painel.add(new JLabel("Idade:"), c);
        c.gridx = 1;
        txtIdade = new JTextField(20);
        painel.add(txtIdade, c);

        // Apelido
        c.gridx = 0;
        c.gridy = 2;
        painel.add(new JLabel("Apelido:"), c);
        c.gridx = 1;
        txtApelido = new JTextField(20);
        painel.add(txtApelido, c);

        // Botão
        c.gridx = 0;
        c.gridy = 3;
        c.gridwidth = 2; // botão ocupa duas colunas
        btnCriar = new JButton("Criar Pessoa");
        painel.add(btnCriar, c);

        add(painel);

        // Evento do botão
        btnCriar.addActionListener(e -> {
            String nome = txtNome.getText();
            int idade = Integer.parseInt(txtIdade.getText());
            String apelido = txtApelido.getText();

            JOptionPane.showMessageDialog(this, "Pessoa criada: " + nome + " (" + apelido + "), " + idade + " anos.");

            try (FileWriter writer = new FileWriter("pessoas.csv", true)) {
                writer.write(nome + "," + idade + "," + apelido + "\n");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar no CSV!");
            }
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        SwingUtilities.invokeLater(() -> {
            PessoaFrame frame = new PessoaFrame();
            frame.setVisible(true);
        });
    }
}

// Variables declaration - do not modify
// End of variables declaration

