
DROP USER IF EXISTS 'ryan'@'localhost';

CREATE USER 'ryan'@'localhost' IDENTIFIED BY 'pass123';

GRANT ALL PRIVILEGES ON MUSICA.* TO 'ryan'@'localhost';

FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS MUSICA;
CREATE DATABASE MUSICA;
USE MUSICA;
CREATE TABLE PESSOA(
id INT PRIMARY KEY auto_increment,
nome VARCHAR (250),
idade INT,
apelido VARCHAR (250)
)
;
SELECT * FROM PESSOA;

CREATE TABLE CIDADE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    lugar VARCHAR(255),
    populacao INT,
    pessoa VARCHAR(255)
);
SELECT * FROM CIDADE;

CREATE TABLE COMIDA(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255),
    tipo VARCHAR(255),
    preco DOUBLE
);
SELECT * FROM COMIDA;
